### ISSUE TITLE
Current Status

### ISSUE THREAD

**Issue by yabirgb** [wolfhund/falcon-oauth#35]
Hi I want to implement an ouath2 server with falcon and could be useful to use this project. Is there documentation on what is done and what needs to be completed?

**Comment by wolfhund** [comment]
Hello, thanks for reaching out the issue channel. I have not being able to update this project as frequently as I wanted, but I will add more features to it and update it to support the current version of Falcon. Feel free to make a fork from this project and send PRs if you desire.

Currently, this project has implementation for OAuth2 authentication with Client Credentials and Authorization Code grant types. I do not have other documentation other than the docstrings at the moment, but it is also a feature that I would like to add.

Let me know if you have any questions.

Regards.

**Comment by yabirgb** [comment]
Thank you @wolfhund . OAuth2 is just what I need so thank you for your effort. I'll work on the project and If I find any issue I'll PR the project :D

**Comment by wolfhund** [comment]
Thanks a lot :)
